[project]

name = "pydantic_core_app"
version = "1.0.0"
description = ""
authors = [{name = "Flet Developer", email = "your@email.com"}]
dependencies = ["flet==0.25.0.dev3673", "pydantic_core"]

[tool.flet]
android.adaptive_icon_background = "#ffffff"