[project]

name = "time_machine_app"
version = "1.0.0"
description = ""
authors = [{name = "Flet Developer", email = "your@email.com"}]
dependencies = ["flet==0.25.0.dev3673", "time-machine"]

[tool.flet]
android.adaptive_icon_background = "#ffffff"