[project]

name = "google-crc32_app"
version = "1.0.0"
description = ""
authors = [{name = "Flet Developer", email = "your@email.com"}]
dependencies = ["flet==0.25.2", "google_crc32c"]

[tool.flet]
android.adaptive_icon_background = "#ffffff"